# Generated by Django 5.2.11 on 2026-09-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['semester', 'name']},
        ),
    ]
